"""followers

Revision ID: 757255604061
Revises: 4980d34bc80b
Create Date: 2019-07-18 23:22:11.271045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '757255604061'
down_revision = '4980d34bc80b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folowers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('folowers')
    # ### end Alembic commands ###
